# Generated by Django 4.2.8 on 2024-03-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_details", models.CharField(max_length=130)),
                ("work_date", models.DateField()),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                ("status_updated", models.DateTimeField(blank=True, null=True)),
                ("paid_amount", models.IntegerField(default=0)),
                ("comm_amount", models.IntegerField(default=0)),
                ("emp_amount", models.IntegerField(default=0)),
                (
                    "department_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.department",
                    ),
                ),
            ],
        ),
    ]
