# Generated by Django 4.2.8 on 2024-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_application",
            name="is_feedback",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="job_application",
            name="is_rated",
            field=models.BooleanField(default=0),
        ),
    ]
