# Generated by Django 4.2.8 on 2024-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0003_job_application_is_feedback_job_application_is_rated"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_application",
            name="is_rating",
            field=models.IntegerField(default=0),
        ),
    ]
