# Generated by Django 4.2.8 on 2024-03-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0004_job_application_is_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job_application",
            old_name="is_rating",
            new_name="rating",
        ),
    ]
