# Generated by Django 4.2.8 on 2024-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0005_rename_is_rating_job_application_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_application",
            name="feedback_details",
            field=models.CharField(default="", max_length=230),
            preserve_default=False,
        ),
    ]
