# Generated by Django 4.2.8 on 2024-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0006_job_application_feedback_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_application",
            name="feedback_details",
            field=models.CharField(max_length=230, null=True),
        ),
    ]
