# Generated by Django 4.2.8 on 2024-03-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0008_alter_job_application_comm_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_application",
            name="comm_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="job_application",
            name="emp_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="job_application",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
